openapi: '3.0.0'
info:
  version: 1.0.0
  title: Contact List
servers:
  - url: http://localhost:8080
paths:
  /contact/get-contact-list:
    get:
      summary: Get Contact List
      operationId: getContactList
      tags:
        - contact
      responses:
        '200':
          description: Contact List
          content:
            application/json:
              schema:
                type: 'array'
                items:
                  $ref: '#/components/schemas/Contact'

  /contact/get-contact/{contactId}:
    get:
      summary: Get Contact by id
      operationId: getContact
      tags:
        - contact
      parameters:
        - in: path
          name: contactId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Contact
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'

  /contact/new-contact:
    post:
      summary: Create new Contact
      operationId: createContact
      requestBody:
        description: The new Contact
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      tags:
        - contact
      responses:
        '200':
          description: Created

  /contact/update-contact/{contactId}:
    patch:
      summary: Update Contact
      operationId: updateContact
      requestBody:
        description: The Contact
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      tags:
        - contact
      parameters:
        - in: path
          name: contactId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Updated

  /contact/remove/{contactId}:
    delete:
      summary: Remove Contact
      operationId: removeContact
      tags:
        - contact
      parameters:
        - in: path
          name: contactId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Removed

components:
  schemas:
    Contact:
      required:
        - id
        - firstName
        - phone
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: number
        address:
          $ref: '#/components/schemas/Address'

    Address:
      required:
        - city
        - street
        - number
      properties:
        city:
          $ref: '#/components/schemas/City'
        street:
          type: string
        number:
          type: string
        zipcode:
          type: string

    City:
      type: string
      enum:
        - Haifa
        - Akko
        - Tel-Aviv
        - Afula

